# Generated by Django 4.2 on 2023-05-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_objectrecruts_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectsPlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=50)),
                ('answers', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectsSitx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.objectsplanet')),
            ],
        ),
    ]
