# Generated by Django 4.2 on 2023-05-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_objectsorder_objectsplanet_objectsquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsquestion',
            name='answers',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ObjectsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answers', models.BooleanField(default=True)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.objectsquestion')),
            ],
        ),
    ]
