# Generated by Django 4.2 on 2023-05-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_objectsquestion_answers_objectsanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsanswers',
            name='answers',
            field=models.BooleanField(null=True),
        ),
    ]
