# Generated by Django 4.2 on 2023-05-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_objectsanswers_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsanswers',
            name='answers',
            field=models.BooleanField(null=True),
        ),
    ]
