# Generated by Django 4.2 on 2023-05-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_objectsanswers_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsanswers',
            name='questions',
            field=models.IntegerField(null=True),
        ),
    ]
